# Generated by Django 4.2.1 on 2023-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_profile_orderentry_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN', 'Initial'), ('CO', 'Completed'), ('DE', 'Delivered')], default='IN', max_length=2),
        ),
    ]
